[build-system]
requires = ["hatchling>=1.24", "hatch-vcs>=0.4"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"                      # derive from git tags
tag_pattern = "^curvpyutils-v(?P<version>.+)$"
fallback-version = "0.0.0"

[tool.hatch.version.raw-options]
root = "../.."
relative_to = "pyproject.toml"

# write a version file on build
[tool.hatch.build.hooks.vcs]
version-file = "src/curvpyutils/_version.py"

[tool.hatch.build.targets.wheel]
packages = ["src/curvpyutils"]

[project]
name = "curvpyutils"
requires-python = ">=3.10"
dynamic = ["version"]
description = "Utility functions for Curv Python packages"
readme = "readme.md"
license = {text = "MIT"}
authors = [{name="Mike Goelzer"}]
classifiers = ["Programming Language :: Python :: 3 :: Only"]
dependencies = []
